version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=metofficett_metdemo1
      - MYSQL_USER=metofficett_metdemo
      - MYSQL_PASSWORD=F+qgvL9f-_Bc
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=1
      - PHP_DISPLAY_STARTUP_ERRORS=1
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=metofficett_metdemo1
      - MYSQL_USER=metofficett_metdemo
      - MYSQL_PASSWORD=F+qgvL9f-_Bc
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=metofficett_metdemo
      - PMA_PASSWORD=F+qgvL9f-_Bc
    depends_on:
      - db

volumes:
  db_data:
